CPPFLAGS += __FREERTOS__
CFLAGS += -O0 -Wno-format-truncation -Wno-pointer-sign -Wno-parentheses -Wno-switch -Wno-maybe-uninitialized -Wno-unused-const-variable
COMPONENT_ADD_LDFLAGS += --gc-sections
COMPONENT_ADD_INCLUDEDIRS += .
COMPONENT_OBJS := aac_ac3_parser.o \
			aac_parser.o \
			aacdec.o \
			aacps_common.o \
			aacps_tables.h \
			aacps_float.o \
			aacpsdsp_float.o \
			aacsbr.o \
			aactab.o \
			ac3.o \
			ac3_channel_layout_tab.o \
			ac3_parser.o \
			ac3dec_data.o \
			ac3dec_float.o \
			ac3dsp.o \
			ac3tab.o \
			acelp_filters.o \
			acelp_vectors.o \
			adts_header.o \
			adts_parser.o \
			alac.o \
			alac_data.o \
			alacdsp.o \
			allcodecs.o \
			alsdec.o \
			apedec.o \
			atrac.o \
			atrac1.o \
			atrac3.o \
			audiodsp.o \
			avcodec.o \
			avdct.o \
			avfft.o \
			avpacket.o \
			bgmc.o \
			bitstream.o \
			bitstream_filters.o \
			bsf.o \
			bswapdsp.o \
			cbrt_tables.h \
			cbrt_data.o \
			celp_filters.o \
			codec_desc.o \
			codec_par.o \
			cook_parser.o \
			cos_tables.o \
			cos_tables.o \
			d3d11va.o \
			dca.o \
			dca_exss.o \
			dca_parser.o \
			dca_sample_rate_tab.o \
			dct.o \
			dct32_fixed.o \
			dct32_float.o \
			decode.o \
			dirac.o \
			dsd.o \
			dsddec.o \
			dv_profile.o \
			eac3_data.o \
			encode.o \
			exif.o \
			faandct.o \
			faanidct.o \
			fdctdsp.o \
			fft_fixed_32.o \
			fft_float.o \
			fft_init_table.o \
			flac.o \
			flac_parser.o \
			flacdata.o \
			flacdec.o \
			flacdsp.o \
			fmtconvert.o \
			get_buffer.o \
			golomb.o \
			gsm_parser.o \
			gsmdec.o \
			gsmdec_data.o \
			idctdsp.o \
			imgconvert.o \
			jfdctfst.o \
			jfdctint.o \
			jni.o \
			jrevdct.o \
			kbdwin.o \
			latm_parser.o \
			lossless_audiodsp.o \
			lsp.o \
			mathtables.o \
			mdct15.o \
			mdct_float.o \
			mdct_fixed_32.o \
			mediacodec.o \
			mlz.o \
			mpc.o \
			mpc7.o \
			mpc8.o \
			mpeg12framerate.o \
			mpeg4audio.o \
			mpeg4audio_sample_rates.o \
			mpegaudio.o \
			mpegaudio_parser.o \
			mpegaudiodata.o \
			mpegaudiodec_common_tables.h \
			mpegaudiodec_common.o \
			mpegaudio_tables.h \
			mpegaudiodec_fixed.o \
			mpegaudiodec_float.o \
			mpegaudiodecheader.o \
			mpegaudiodsp.o \
			mpegaudiodsp_data.o \
			mpegaudiodsp_fixed.o \
			mpegaudiodsp_float.o \
			mpegaudiotabs.o \
			msgsmdec.o \
			options.o \
			opus.o \
			opus_celt.o \
			opus_parse.o \
			opus_pvq.o \
			opus_rc.o \
			opus_silk.o \
			opusdec.o \
			opusdec_celt.o \
			opusdsp.o \
			opustab.o \
			parser.o \
			parsers.o \
			pcm-bluray.o \
			pcm-dvd.o \
			pcm_tables.h \
			pcm.o \
			profiles.o \
			pthread.o \
			pthread_frame.o \
			pthread_slice.o \
			qsv_api.o \
			ra144.o \
			ra144dec.o \
			ra288.o \
			ralf.o \
			raw.o \
			rdft.o \
			sbrdsp.o \
			shorten.o \
			simple_idct.o \
			sinewin_tables.h \
			sinewin.o \
			tak.o \
			tak_parser.o \
			takdec.o \
			takdsp.o \
			tiff_common.o \
			tta.o \
			ttadata.o \
			ttadsp.o \
			utils.o \
			version.o \
			vlc.o \
			vorbis.o \
			vorbis_data.o \
			vorbis_parser.o \
			vorbisdec.o \
			vorbisdsp.o \
			wavpack.o \
			wavpackdata.o \
			wma.o \
			wma_common.o \
			wma_freqs.o \
			wmadec.o \
			wmalosslessdec.o \
			wmaprodec.o \
			wmavoice.o \
			xiph.o \
			to_upper4.o
COMPONENT_SRCDIRS := libavcodec
COMPONENT_ADD_INCLUDEDIRS := libavcodec
