CPPFLAGS += __FREERTOS__
CFLAGS += -O0 -Wno-format-truncation -Wno-pointer-sign -Wno-parentheses -Wno-switch -Wno-maybe-uninitialized
COMPONENT_ADD_LDFLAGS += --gc-sections
COMPONENT_ADD_INCLUDEDIRS += .
COMPONENT_OBJS := adler32.o \
			aes.o \
			aes_ctr.o \
			audio_fifo.o \
			avsscanf.o \
			avstring.o \
			base64.o \
			blowfish.o \
			bprint.o \
			buffer.o \
			camellia.o \
			cast5.o \
			channel_layout.o \
			color_utils.o \
			cpu.o \
			crc.o \
			csp.o \
			des.o \
			detection_bbox.o \
			dict.o \
			display.o \
			dovi_meta.o \
			downmix_info.o \
			encryption_info.o \
			error.o \
			eval.o \
			fifo.o \
			file.o \
			file_open.o \
			film_grain_params.o \
			fixed_dsp.o \
			float_dsp.o \
			frame.o \
			hash.o \
			hdr_dynamic_metadata.o \
			hdr_dynamic_vivid_metadata.o \
			hmac.o \
			hwcontext.o \
			hwcontext_stub.o \
			imgutils.o \
			integer.o \
			intmath.o \
			lfg.o \
			lls.o \
			log.o \
			log2_tab.o \
			lzo.o \
			mastering_display_metadata.o \
			mathematics.o \
			md5.o \
			mem.o \
			murmur3.o \
			opt.o \
			parseutils.o \
			pixdesc.o \
			pixelutils.o \
			random_seed.o \
			rational.o \
			rc4.o \
			reverse.o \
			ripemd.o \
			samplefmt.o \
			sha.o \
			sha512.o \
			slicethread.o \
			spherical.o \
			stereo3d.o \
			tea.o \
			threadmessage.o \
			av_time.o \
			timecode.o \
			tree.o \
			twofish.o \
			tx.o \
			tx_double.o \
			tx_float.o \
			tx_int32.o \
			utils.o \
			uuid.o \
			version.o \
			video_enc_params.o \
			xga_font_data.o \
			xtea.o
COMPONENT_SRCDIRS := libavutil
COMPONENT_ADD_INCLUDEDIRS := libavutil